# Generated by Django 5.0.7 on 2024-08-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pub_image',
            field=models.ImageField(default=None, null=True, upload_to='publications/', verbose_name='publication image'),
        ),
    ]
