# Generated by Django 5.0.7 on 2024-08-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publication',
            table='publications',
        ),
    ]
